### PR TITLE
Lift library operations into Accelerate as well

### PR DESCRIPTION
**Pull request by tmcdonell**
A while ago I was working on [a little app in accelerate](https://github.com/tmcdonell/accelerate-lulesh) and realised that the operations from your 'linear' package were exactly what I needed. This package sounded great, but only made the datatypes available to accelerate, not the operations themselves. This patch is an attempt to do the latter as well.

I'm just creating this pull request now to get the ball rolling, but there are a couple TODOs...
- [ ] I had to redefine several classes such as [R3](https://github.com/tmcdonell/linear-accelerate/blob/master/src/Data/Array/Accelerate/Linear/V3.hs#L69) so that the types work out. This makes it a little awkward though, because, for example, you'll need to use a different version of `_z` depending on whether you have an `Exp (R3 a)` (this package) vs. `R3 (Exp a)` (linear package). I find that a little unsatisfactory, but am not sure if there is a better way. Do you have any suggestions?
- [ ] This was designed against accelerate HEAD, not the current released version. I could backport to the released version as well if you like, or just don't merge/upload this in until I've updated the Hackage release; your call.
- [ ] Does not have full library coverage yet. I might be able to find time to do this now, or we could just wait until people complain...
- [ ] Since this is basically a rewrite, I'm happy to be in charge of maintenance if you like.

### CODE REVIEW

**Comment by tmcdonell** [comment]
This doesn't have full coverage but I think is fine for now.

I'll be uploading a compatible release of Accelerate in the next day or so. If you could upload this to Hackage as well that would be greatly appreciated. Thanks!

**Comment by tmcdonell** [comment]
After much delay, accelerate-1.0 is now on Hackage (and the example programs depend on this new version of linear-accelerate).

(CC @RyanGlScott)

**Comment by RyanGlScott** [comment]
Indeed, it would be nice to get this updated, as the version of `linear-accelerate` that's on Stackage [will probably be removed soon](https://travis-ci.org/fpco/stackage/builds/217104086#L229) due to its out-of-date upper version bound on `accelerate`.

**Comment by ekmett** [comment]
I've merged at least to indicate an intent to distribute based on this version, but I haven't yet had a chance to go through the changes in any detail.

**Comment by ekmett** [comment]
@RyanGlScott: If you're comfortable with the changes, then I'll take them as is. This package has been languishing a while.

**Comment by RyanGlScott** [comment]
Personally, I'd vote to make @tmcdonell a co-maintainer of `linear-accelerate`, especially since he pretty much rewrote much of it for this PR :)

**Comment by ekmett** [comment]
I do think there's probably a better way than the refined R3, etc classes, but I'm willing to bite the bullet until we figure it out.

**Comment by ekmett** [comment]
Sold.

**Comment by ekmett** [comment]
@tmcdonell you should now have access to the repository here to push changes directly.

**Comment by ekmett** [comment]
And you now have access to push the package to hackage. I leave it in your capable hands for now. =)

**Comment by ekmett** [comment]
If you could `git tag` the released version when it goes out it'd be helpful.

**Comment by tmcdonell** [comment]
Thanks! Tagged and released as [linear-accelerate-0.3](http://hackage.haskell.org/package/linear-accelerate-0.3) (:

**Pull request merged**
